# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "sanjay-14/node-typescript-boilerplate"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build_test_image: &build
    title: "Building Test Docker image"
    type: "build"
    image_name: "sanjay-14/node-typescript-boilerplate"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-TEST"
    dockerfile: "Dockerfile"
    stage: "build"
    target: dev

  build_deploy_image:
    <<: *build
    title: "Building Deploy image"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    target: prod-env
    when:
      steps:
        - name: build_test_image
          on:
            - success
      branch:
        only:
          - master
  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "${{build_test_image}}" # The image in which command will be executed
    working_directory: /app # Running command where code cloned
    commands:
      - "npm run test"
    stage: "test"
    when:
      steps:
        - name: build_test_image
          on:
            - success
  
  deploy:
    stage: deploy
    title: Deploy to QA
    image: ${{build_deploy_image}}
    working_directory: /app
    environment:
      - 'NODE_ENV=production'
      - 'PORT=80'
    commands:
      - ls
    when:
      branch:
        only:
          - master
      steps:
        - name: build_deploy_image
          on:
            - success   
        - name: test
          on:
            - success            